# http://travis-ci.org/#!/RDFLib/rdflib_zodb
language: python
# whitelist
branches:
  only:
    - master

#python:
#    - 2.6
#    - 2.7
#    - 3.2
#    - 3.3

matrix:
    include:
        - python: 2.6 
          env: REQUIREMENTS=requirements.py2.txt
        - python: 2.7
          env: REQUIREMENTS=requirements.py2.txt
        - python: 3.2
          env: REQUIREMENTS=requirements.py3.txt
        - python: 3.3
          env: REQUIREMENTS=requirements.py3.txt

install:
    - pip install --use-mirrors --default-timeout 60 -r $REQUIREMENTS
    - python setup.py install

before_script:
    - flake8 --exit-zero rdflib_zodb

script:
    - nose2
